################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

variables:
  GITHUB_PROJECT_NAME: "DiHydrogen"
  GITHUB_PROJECT_ORG: "LLNL"
  # Use an LLNL service user to run CI. This prevents from running pipelines as
  # an actual user.
  #FIXME: lbannusr says unauthorized
  LLNL_SERVICE_USER: "lbannusr"
  # Use a service user workspace. Solves permission issues, stores everything
  # at the same location whoever triggers a pipeline.
  #  CUSTOM_CI_BUILDS_DIR: ""
  # Tells Gitlab to recursively update the submodules when cloning the project.
  GIT_SUBMODULE_STRATEGY: recursive
  # We build the projects in the CI clone directory.
  # TODO: add a clean-up mechanism
  BUILD_ROOT: ${CI_PROJECT_DIR}
  # Set the build-and-test command.
  BUILD_AND_TEST_CMD: "./scripts/gitlab/build_and_test.sh"
  # Override the list of branch that will skip the "draft PR test".
  # Add protected branches here. Defaults to "develop main master".
  ALWAYS_RUN_LIST: "develop"

stages:
  - machine-checks
  - build-and-test

# Template for jobs triggering a build-and-test sub-pipelines:
.build-and-test:
  stage: build-and-test
  trigger:
    include:
      - local: '.gitlab/custom-jobs-and-variables.yml'
      - project: 'radiuss/radiuss-shared-ci'
        ref: 6b4a2a1
        file: '${CI_MACHINE}-build-and-test.yml'
      - local: '.gitlab/${CI_MACHINE}-build-and-test-extra.yml'
    strategy: depend
    forward:
      pipeline_variables: true

include:
  # [Optional] checks preliminary to running the actual CI test
  #- project: 'radiuss/radiuss-shared-ci'
  #  ref: v2022.12.0
    #file: 'preliminary-ignore-draft-pr.yml'
  # pipelines subscribed by the project
  - local: .gitlab/subscribed-pipelines.yml
