################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - run-all-clusters

corona testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/build-and-test-corona.yml
    forward:
      pipeline_variables: true

lassen testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/build-and-test-lassen.yml
    forward:
      pipeline_variables: true

pascal testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: '/.gitlab/build-and-test-pascal.yml'
    forward:
      pipeline_variables: true

quartz testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: '/.gitlab/build-and-test-quartz.yml'
    forward:
      pipeline_variables: true

tioga testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/build-and-test-tioga.yml
    forward:
      pipeline_variables: true
