################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

gcc-8-3-1-cuda-11-7-0:
  variables:
    SPEC: "%gcc@8.3.1 +developer +cuda cuda_arch=70 ^cuda@11.7.0"
    MODULES: "gcc/8.3.1 spectrum-mpi/rolling-release cuda/11.7.0"
  extends: .build-and-test-on-lassen

gcc-8-3-1-cuda-11-8-0:
  variables:
    SPEC: "%gcc@8.3.1 +developer +cuda cuda_arch=70 ^cuda@11.8.0"
    MODULES: "gcc/8.3.1 spectrum-mpi/rolling-release cuda/11.8.0"
  extends: .build-and-test-on-lassen

gcc-8-3-1-cuda-12-0-0:
  variables:
    SPEC: "%gcc@8.3.1 +developer +cuda cuda_arch=70 ^cuda@12.0.0"
    MODULES: "gcc/8.3.1 spectrum-mpi/rolling-release cuda/12.0.0"
  extends: .build-and-test-on-lassen

clang-13-0-1-gcc-8-3-1-cuda-11-8-0:
  variables:
    SPEC: "clang@13.0.1-gcc-8.3.1 +developer +cuda cuda_arch=70 ^cuda@11.8.0"
    MODULES: "clang/13.0.1-gcc-8.3.1 spectrum-mpi/rolling-release cuda/11.8.0"
  extends: .build-and-test-on-lassen

clang-13-0-1-gcc-8-3-1-cuda-12-0-0:
  variables:
    SPEC: "clang@13.0.1-gcc-8.3.1 +developer +cuda cuda_arch=70 ^cuda@12.0.0"
    MODULES: "clang/13.0.1-gcc-8.3.1 spectrum-mpi/rolling-release cuda/12.0.0"
  extends: .build-and-test-on-lassen

.build-and-test-on-lassen:
  stage: build
  variables:
    LLNL_LSF_SCHEDULER_PARAMETERS: "-q pdebug -nnodes 1 -W 10"
  tags: [lassen, batch]
  extends: .build-and-test
