################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

gcc-11-2-1-cuda-11-8-0-pascal:
  variables:
    COMPILER_FAMILY: gnu
    MODULES: "gcc/11.2.1-magic openmpi/4.1.2 cuda/11.8.0"
  extends: [.build-and-test-on-pascal, .build-and-test]

clang-14-0-6-cuda-11-8-0-pascal:
  variables:
    COMPILER_FAMILY: clang
    MODULES: "clang/14.0.6-magic openmpi/4.1.2 cuda/11.8.0"
  extends: [.build-and-test-on-pascal, .build-and-test]

gcc-11-2-1-cuda-11-8-0-coverage-pascal:
  variables:
    COMPILER_FAMILY: gnu
    MODULES: "gcc/11.2.1-magic openmpi/4.1.2 cuda/11.8.0 python"
    WITH_COVERAGE: "1"
  extends: [.build-and-test-on-pascal, .build-and-test-coverage]

.build-and-test-on-pascal:
  stage: build
  tags: [pascal, batch]
