################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

rocm-6-1-2:
  variables:
    MODULES: "PrgEnv-cray rocm/6.1.2 cray-mpich cray-libsci"
  extends: .build-and-test-on-tioga

rocm-6-1-2-distconv:
  variables:
    MODULES: "PrgEnv-cray rocm/6.1.2 cray-mpich cray-libsci"
    WITH_DISTCONV: "1"
  extends: .build-and-test-on-tioga
  rules:
    - if: $TEST_DISTCONV_BUILD == "1"

.build-and-test-on-tioga:
  stage: build
  tags: [tioga, batch]
  variables:
    LLNL_FLUX_SCHEDULER_PARAMETERS: "-N1 -t 20 -q pci"
  extends: .build-and-test
