################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

default:
  id_tokens:
     SITE_ID_TOKEN:
        aud: https://lc.llnl.gov/gitlab

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

# Note: We load gcc/10.3.1-magic to get the right MPI but it's not
# (directly) used.
#
# Note: There are issues with /usr/tce/bin/python3 (the default) and
# build systems (in particular, it's not clear that all the
# includes/libs are setup properly under the "/usr/tce" prefix). So I
# load a module to get a real prefix.
rocm-6-0-2-corona:
  variables:
    COMPILER_FAMILY: amdclang
    MODULES: "gcc/10.3.1-magic mvapich2/2.3.7 rocm/6.0.2 cmake/3.26.3 python"
  extends: [.build-and-test-on-corona, .build-and-test]

gcc-12-1-1-cpu-corona:
  variables:
    COMPILER_FAMILY: gnu
    MODULES: "gcc/12.1.1-magic mvapich2/2.3.7 cmake/3.26.3 python"
  extends: [.build-and-test-on-corona, .build-and-test]

clang-14-0-6-cpu-corona:
  variables:
    COMPILER_FAMILY: clang
    MODULES: "clang/14.0.6-magic mvapich2/2.3.7 cmake/3.26.3 python"
  extends: [.build-and-test-on-corona, .build-and-test]

gcc-11-2-1-coverage-cpu-corona:
  variables:
    COMPILER_FAMILY: gnu
    MODULES: "gcc/11.2.1-magic mvapich2/2.3.7 cmake/3.26.3 python"
    WITH_COVERAGE: "1"
  extends: [.build-and-test-on-corona, .build-and-test-coverage]

.build-and-test-on-corona:
  stage: build
  tags: [corona, batch]
