################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

clang-16-0-6-gcc-11-2-1-cuda-12-2-2-lassen:
  variables:
    MODULES: "clang/16.0.6-gcc-11.2.1 spectrum-mpi/rolling-release cuda/12.2.2 cmake/3.29.2 python/3.8.2"
  extends: .build-and-test-on-lassen

clang-16-0-6-gcc-11-2-1-cuda-12-2-2-distconv-lassen:
  variables:
    MODULES: "clang/16.0.6-gcc-11.2.1 spectrum-mpi/rolling-release cuda/12.2.2 cmake/3.29.2 python/3.8.2"
    WITH_DISTCONV: "1"
  extends: .build-and-test-on-lassen
  rules:
    - if: $TEST_DISTCONV_BUILD == "1"

.build-and-test-on-lassen:
  stage: build
  tags: [lassen, batch]
  extends: .build-and-test
