################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

# Note: We load gcc/10.3.1-magic to get the right MPI but it's not
# (directly) used.
rocm-5-4-3:
  variables:
    SPEC: "%rocmcc@5.4.3 +developer +rocm amdgpu_target=gfx90a ^hip@5.4.3 ^llvm-amdgpu@5.4.3 ^hsa-rocr-dev@5.4.3"
    MODULES: "PrgEnv-amd amd/5.4.3"
  extends: .build-and-test-on-tioga

rocm-5-5-0:
  variables:
    SPEC: "%rocmcc@5.5.0 +developer +rocm amdgpu_target=gfx90a ^hip@5.5.0 ^llvm-amdgpu@5.5.0 ^hsa-rocr-dev@5.5.0"
    MODULES: "PrgEnv-amd amd/5.5.0"
  extends: .build-and-test-on-tioga

# cray-amd-5-5-0:
#   variables:
#     SPEC: "%cce@amd-5.5.0 +developer +rocm amdgpu_target=gfx90a ^hip@5.5.0 ^llvm-amdgpu@5.5.0 ^hsa-rocr-dev@5.5.0"
#   extends: .build-and-test-on-tioga

.build-and-test-on-tioga:
  stage: build
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "-N1 -t 10"
    LLNL_FLUX_SCHEDULER_PARAMETERS: "-N1 -t 10"
  tags: [tioga, batch]
  extends: .build-and-test
