################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

# Note: We load gcc/10.3.1-magic to get the right MPI but it's not
# (directly) used.
#
# Note: There are issues with /usr/tce/bin/python3 (the default) and
# build systems (in particular, it's not clear that all the
# includes/libs are setup properly under the "/usr/tce" prefix). So I
# load a module to get a real prefix. This only matters when
# "+ci+coverage".

rocm-6-0-2-corona:
  variables:
    MODULES: "gcc/10.3.1-magic openmpi/4.1.2 rocm/6.0.2 python"
  extends: [.build-and-test-on-corona, .build-and-test]

rocm-6-0-2-distconv-corona:
  variables:
    MODULES: "gcc/10.3.1-magic openmpi/4.1.2 rocm/6.0.2 python"
    WITH_DISTCONV: "1"
  extends: [.build-and-test-on-corona, .build-and-test]
  rules:
    - if: $TEST_DISTCONV_BUILD == "1"

rocm-6-0-2-coverage-corona:
  variables:
    MODULES: "gcc/10.3.1-magic openmpi/4.1.2 rocm/6.0.2 python"
    WITH_COVERAGE: "1"
  extends: [.build-and-test-on-corona, .build-and-test-coverage]

.build-and-test-on-corona:
  stage: build
  tags: [corona, batch]
