################################################################################
## Copyright 2019-2023 Lawrence Livermore National Security, LLC and other
## DiHydrogen Project Developers. See the top-level LICENSE file for details.
##
## SPDX-License-Identifier: Apache-2.0
################################################################################

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

gcc-10-3-1-cuda-11-7-0:
  variables:
    SPEC: "%gcc@10.3.1 +developer +cuda cuda_arch=60 ^cuda@11.7.0"
    MODULES: "gcc/10.3.1-magic openmpi/4.1.2 cuda/11.7.0 ninja/1.11.0"
  extends: .build-and-test-on-pascal

gcc-10-3-1-cuda-11-8-0:
  variables:
    SPEC: "%gcc@10.3.1 +developer +cuda cuda_arch=60 ^cuda@11.8.0"
    MODULES: "gcc/10.3.1-magic openmpi/4.1.2 cuda/11.8.0 ninja/1.11.0"
  extends: .build-and-test-on-pascal

.build-and-test-on-pascal:
  stage: build
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "-N1 -p pbatch -t 10"
  tags: [pascal, batch]
  extends: .build-and-test
